version: '3.8'

services:
  # ---------- POSTGRES ----------
  postgres:
    image: postgres:16
    container_name: swifttrack-postgres
    environment:
      POSTGRES_DB: swifttrack
      POSTGRES_USER: swift
      POSTGRES_PASSWORD: swiftpass
    ports:
      - "5433:5432"
    volumes:
      - swifttrack_pgdata:/var/lib/postgresql/data

  # ---------- ZOOKEEPER ----------
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: swifttrack-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  # ---------- KAFKA ----------
  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: swifttrack-kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: swifttrack-zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

volumes:
  swifttrack_pgdata:

#log into the swifttrack
#docker exec -it swifttrack-postgres psql -U swift -d swifttrack --> cmd