#------ Application Info ------
spring.application.name=swifttrack-api
server.port=8080

#-------------POSTGRES---------------------------------------

spring.datasource.url=jdbc:postgresql://localhost:5433/swifttrack
spring.datasource.username=swift
spring.datasource.password=swiftpass

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

#------------------KAFKA-----------------------------
spring.kafka.bootstrap-servers=localhost:9092

# Producer
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

# Consumer
spring.kafka.consumer.group-id=${spring.application.name}
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.properties.spring.json.trusted.packages=*

#------ External Services ------
# Use mock services for local development (true) or real services (false)
service.use-mock=true

# ROS Service URL
service.ros.url=http://localhost:8082

# CMS Service URL
service.cms.url=http://localhost:8081

# WMS Service URL
service.wms.url=http://localhost:8083

#------ Logging ------
logging.level.com.example.demo=DEBUG
logging.level.org.springframework.kafka=INFO